---
<% elasticsearch_ips = [ "192.0.2.70", "192.0.2.71", "192.0.2.72", "192.0.2.73", "192.0.2.74", "192.0.2.75", "192.0.2.76", "192.0.2.77" ].slice(0, ENV['MVTV_ELASTICSEARCH_INSTANCE_COUNT'].to_i) %>

name: "<%= ENV['MVTS_BOSH_DEPLOYMENT_NAME'] %>"
director_uuid: "<%= ENV['BOSH_DIRECTOR_UUID'] %>"
releases:
  - name: "logsearch"
    version: "latest"
compilation:
  workers: 1
  network: "default"
  reuse_compilation_vms: true
  cloud_properties: 
    availability_zone: "eu-west-1c"
    instance_type: "c3.large"
update:
  canaries: 1
  canary_watch_time: "30000-120000"  # 30sec min -> 2min max 
  update_watch_time: "30000-120000"
  max_in_flight: 4
  max_errors: 1
networks:
  - name: "default"
    type: "manual"
    subnets:
      - range: "192.0.2.64/26" # -]192.0.2.127
        name: "default"
        static:
          # redis is reserved so parsers know who to talk to
          - "192.0.2.65"
          # elasticsearch ones are reserved so they can find each other
          - <%= elasticsearch_ips.join("\n          - ") %>
        cloud_properties:
          security_groups:
            - "sg-abcd1234"
          subnet: "subnet-abcd1234"
resource_pools:
  - name: "queue"
    network: "default"
    size: 1
    stemcell:
      name: "bosh-aws-xen-ubuntu-trusty-go_agent-hvm"
      version: "latest"
    cloud_properties:
      availability_zone: "eu-west-1c"
      instance_type: "<%= ENV['MVTV_QUEUE_INSTANCE_TYPE'] %>"
  - name: "ingestor_archiver"
    network: "default"
    size: 2
    stemcell:
      name: "bosh-aws-xen-ubuntu-trusty-go_agent-hvm"
      version: "latest"
    cloud_properties:
      availability_zone: "eu-west-1c"
      instance_type: "c3.xlarge"
  - name: "parser"
    network: "default"
    size: <%= ENV['MVTV_PARSER_INSTANCE_COUNT'] %>
    stemcell:
      name: "bosh-aws-xen-ubuntu-trusty-go_agent-hvm"
      version: "latest"
    cloud_properties:
      availability_zone: "eu-west-1c"
      instance_type: "<%= ENV['MVTV_PARSER_INSTANCE_TYPE'] %>"
  - name: "elasticsearch"
    network: "default"
    size: <%= ENV['MVTV_ELASTICSEARCH_INSTANCE_COUNT'] %>
    stemcell:
      name: "bosh-aws-xen-ubuntu-trusty-go_agent-hvm"
      version: "latest"
    cloud_properties:
      availability_zone: "eu-west-1c"
      instance_type: "<%= ENV['MVTV_ELASTICSEARCH_INSTANCE_TYPE'] %>"
disk_pools:
  - name: "queue"
    disk_size: 16384
    cloud_properties:
      type: "gp2"
  - name: "elasticsearch"
    disk_size: 65536
    cloud_properties:
      type: "gp2"
jobs:
  - name: "queue"
    templates: 
      - release: "logsearch"
        name: "queue"
    instances: 1
    resource_pool: "queue"
    persistent_disk_pool: "queue"
    networks:
      - name: "default"
        static_ips:
          - "192.0.2.65"
  - name: "ingestor_archiver"
    templates: 
      - release: "logsearch"
        name: "ingestor_archiver"
    instances: 2
    resource_pool: "ingestor_archiver"
    networks:
      - name: "default"
  - name: "parser"
    templates:
    - release: "logsearch"
      name: "log_parser"
    instances: <%= ENV['MVTV_PARSER_INSTANCE_COUNT'] %>
    resource_pool: "parser"
    networks:
      - name: "default"
  - name: "elasticsearch"
    templates: 
      - release: "logsearch"
        name: "elasticsearch"
    instances: <%= ENV['MVTV_ELASTICSEARCH_INSTANCE_COUNT'] %>
    resource_pool: "elasticsearch"
    persistent_disk_pool: "elasticsearch"
    networks:
      - name: "default"
        static_ips:
          - <%= elasticsearch_ips.join("\n          - ") %>
properties: 
  elasticsearch:
    cluster_name: "logsearch-perftest"
    host: "<%= elasticsearch_ips.join(',') %>"
    flush_size: <%= ENV['MVTV_LOGSTASH_FLUSH_SIZE'] %>
    discovery:
      minimum_master_nodes: <%= ENV['MVTV_ELASTICSEARCH_INSTANCE_COUNT'] %>
  redis:
    host: "192.0.2.65"
    key: "logstash"
  logstash:
    metadata_level: "DEBUG"
  logstash_parser:
    filters: |
            <%= File.read('etc/logstash-filters.conf').gsub(/^/, '            ').strip %>
apply_spec:
  properties:
    ntp:
      - "0.europe.pool.ntp.org"
      - "1.europe.pool.ntp.org"
      - "2.europe.pool.ntp.org"
      - "3.europe.pool.ntp.org"
