trials: 1
variables:
  queue_instance_type:
    - "m3.xlarge"
  elasticsearch_instance_type:
    - "r3.xlarge"
  elasticsearch_instance_count:
    - 4
  shards:
    - 4
  parser_instance_type:
    - "c4.2xlarge"
  parser_instance_count:
    - 8
  logstash_flush_size:
    - 250
    - 500
    - 1000
settings:
  logsearch:
    api: api.logsearch.example.io:9200
    ingestor: ingestor.logsearch.example.io:443
    ssl_ca_certificate: |
      -----BEGIN CERTIFICATE-----
      ...something-cryptographic...
      -----END CERTIFICATE-----
steps:
  - bosh: deploy
  - custom: put-elasticsearch-template
  - util: timer-mark
    args: start
  - util: sleep
    args: 360
  - custom: push-test-logs
  - custom: wait-for-queue
  - util: sleep
    args: 360
  - util: timer-mark
    args: stop
  - logsearch: dump-metrics
  - custom: dump-custom-metrics
  - aws: dump-metrics
  - bosh: destroy
